---
#tasks for security group
- name: Creating security group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ security_groups }}'



- name: Creating security group rules for harvester,dbserver and webserver
  os_security_group_rule:
    security_group: '{{ item.name }}' 
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}' 
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    state: present
  loop: '{{ security_groups_rules }}'

