---
#Installing dependencies on host system where you are running the ansible script
- name: Install pip
  become: yes
  apt:
    name: ['python-pip'] 
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  
- name: Update pip using pip
  become: yes
  pip:
    name: ['pip']
    state: latest

- name: Install openstack sdk using pip
  become: yes
  pip: 
    name: ['openstacksdk']
    state: latest
